### ISSUE TITLE
How to insert the contents of the sql file into the db?

### ISSUE THREAD

**Issue by MaximilianKohler** [softwareNuggets/PostgreSQL_array_to_string#1]
I watched [your tutorial ](https://www.youtube.com/watch?v=yI3nOUIILE8)but it doesn't say what to do with [that file](https://github.com/softwareNuggets/PostgreSQL_array_to_string/blob/main/create_table_countries.sql). 

I had a quick scroll through your other videos https://www.youtube.com/playlist?list=PLRU_t-SgTrYjx-mY4qlj7bZh9CjbTnsHT but didn't see one that explains it.

For example, I have a file with a bunch of these commands:
```
insert into subscriber_lists (subscriber_id, list_id, status) values (696055, 341, 'confirmed');
insert into subscriber_lists (subscriber_id, list_id, status) values (696058, 341, 'confirmed');
insert into subscriber_lists (subscriber_id, list_id, status) values (696060, 341, 'confirmed');
```
and I can't find simple instructions for how to insert them all at once.

I also noticed that your file is dropping/deleting the table first, which I won't be doing in my case.

**Comment by softwareNuggets** [comment]
Hey,

so you have have a bunch of files that have insert statements,

you want to know how to load these files from the command line?

Scott

**Comment by softwareNuggets** [comment]
did you see this video?

https://www.youtube.com/watch?v=5uRE2KyDTxo&list=PLRU_t-SgTrYjx-mY4qlj7bZh9CjbTnsHT&index=52


you can use this command:
psql -U your_username -d your_database -f your_file.sql

**Comment by MaximilianKohler** [comment]
>so you have have a bunch of files that have insert statements

It would be just one file with a bunch of statements.

I watched the video and looked at the page (_would be convenient to put a link in the video description_) https://github.com/softwareNuggets/POSTGRESQL_load_csv_file_with_array. It's not clear what program you're using to do things, and it's not clear how you created the .csv. You only show the commands needed to import the .csv after it's already created, and it's not clear where we can input/run those commands because we don't know what software you're using.

Anyway, I found out I can simply copy-paste many lines at once into the psql command line, so I don't need to use a file. But if a file is needed I found out you can enter `psql` then do `\e` to get a temporary text file that you can paste things into and it will run the commands after you save and exit.

**Comment by softwareNuggets** [comment]
I added GitHub URL to video description.  Thanks.

So, in that video I was using pgAdmin (postgresql)

Normally, I get data in CSV file format.  I then use microsoft excel to
open a file, and write the "insert statement" into that file.  I have been
a VBA programmer for 20+ years, so, that is my goto get it done easy
programming language.

in this video, I'm just using the raw data.  You do not need the "insert
into table(f1,....) values(..........)   , just the data, separated by a
delimiter, such as a comma.

hope this is helpful.  thank you for viewing video's on my channel.

if you have any suggestions about new video content, I'd appreciate you
sharing your ideas.

Scott

**Comment by MaximilianKohler** [comment]
Interesting. I had major problems when using excel for .csv's _(data getting changed and dropped - related to this https://www.theverge.com/2020/8/6/21355674/human-genes-rename-microsoft-excel-misreading-dates)_ so I switched to only using libreoffice for .csv's. I saw online that lots of other people have the same issues and I saw people recommending using other programs like Modern CSV, or Ron's CSV editor.

**Comment by softwareNuggets** [comment]
when i use Microsoft excel, I don't use the file saveAS CSV.

i write a VBA routine what open's up a file
open "mydata.csv" for output as #1

loop over all the rows in the spreadsheet
    build a string that is comma delimited all the fields i want
          formatting the data correctly, making sure the dates are in
YYYY-MM-DD format, and such
          testing for missing data, is the column in the database nullable?
    write string to file
end loop

close #1
